package com.aimluck.eip.cayenne.om.portlet.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import com.aimluck.eip.cayenne.om.security.TurbineUser;

/**
 * Class _EipTTest was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTTest extends CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String EVALUATION_PROPERTY = "evaluation";
    public static final String NOTE_PROPERTY = "note";
    public static final String TEST_NAME_PROPERTY = "testName";
    public static final String THUMB_ADRESS_PROPERTY = "thumbAdress";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String URL_PROPERTY = "url";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String TURBINE_USER_PROPERTY = "turbineUser";

    public static final String TEST_ID_PK_COLUMN = "TEST_ID";

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setEvaluation(Integer evaluation) {
        writeProperty("evaluation", evaluation);
    }
    public Integer getEvaluation() {
        return (Integer)readProperty("evaluation");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setTestName(String testName) {
        writeProperty("testName", testName);
    }
    public String getTestName() {
        return (String)readProperty("testName");
    }

    public void setThumbAdress(String thumbAdress) {
        writeProperty("thumbAdress", thumbAdress);
    }
    public String getThumbAdress() {
        return (String)readProperty("thumbAdress");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

    public void setUrl(String url) {
        writeProperty("url", url);
    }
    public String getUrl() {
        return (String)readProperty("url");
    }

    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }

    public void setTurbineUser(TurbineUser turbineUser) {
        setToOneTarget("turbineUser", turbineUser, true);
    }

    public TurbineUser getTurbineUser() {
        return (TurbineUser)readProperty("turbineUser");
    }


}
